[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "sweetrpg-web-core"
version = "0.0.697"
description = "Core web framework for SweetRPG services"
readme = "README.md"
license = "MIT"
requires-python = ">= 3.11"
authors = [
    { name = "Paul Schifferer", email = "dm@sweetrpg.com" },
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Web Environment",
    "Framework :: Flask",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Topic :: Software Development :: Libraries :: Application Frameworks",
]
dependencies = [
    "Flask~=3.0",
]

[project.urls]
Documentation = "https://sweetrpg.github.io/web-core"

[project.scripts]
sweetrpg-web-core = "sweetrpg_web_core.cli:main"

[dependency-groups]
test = [
    "asgiref~=3.0",
    "blinker~=1.0",
    "coverage-badge~=1.0",
    "dnspython~=2.8",
    "pytest-cov~=4.0",
    "pytest-env~=1.7",
    "pytest-ordering~=0.6",
    "pytest~=7.0",
    "python-dotenv~=1.0",
]
docs = [
    "Pallets-Sphinx-Themes~=2.0",
    "Sphinx~=8.0",
    "sphinx-issues~=3.0",
    "sphinxcontrib-log-cabinet~=1.0",
    "sphinx-tabs~=3.0",
    "rstcheck~=6.0",
]

[tool.hatch.build.targets.wheel]
packages = ["src/sweetrpg_web_core"]

[tool.pytest.ini_options]
testpaths = ["tests"]
filterwarnings = ["error"]

[tool.coverage.run]
branch = true
source = [
    "sweetrpg_web_core",
    "tests",
]

[tool.coverage.paths]
source = [
    "src",
]

[tool.semantic_release]
version_variable = "src/sweetrpg_web_core/__init__.py:__version__"
branch = "develop"
upload_to_pypi = false
tag_format = "{version}"
