name: CI

on:
    push:
        branches: [develop]
        paths:
            - "src/**"
            - "tests/**"
            - setup.cfg
            - setup.py
            - tox.ini
            - "requirements/**"
            - "docs/**"
            - "pytest.ini"

jobs:
    tests:
        name: ${{ matrix.name }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                include:
                    - {
                          name: Linux,
                          python: "3.9",
                          os: ubuntu-latest,
                          tox: py39,
                      }
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python }}
            - name: update-pip
              run: |
                  pip install -U wheel
                  pip install -U setuptools
                  python -m pip install -U pip
            - name: get-pip-cache-dir
              id: pip-cache
              run: echo "::set-output name=dir::$(pip cache dir)"
            - name: cache-pip
              uses: actions/cache@v2
              with:
                  path: ${{ steps.pip-cache.outputs.dir }}
                  key: pip|${{ runner.os }}|${{ matrix.python }}|${{ hashFiles('setup.py') }}|${{ hashFiles('requirements/*.txt') }}
            - name: install-utils
              run: pip install tox
            - name: tests
              run: tox -e ${{ matrix.tox }}

    docs:
        needs: [tests]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                  python-version: "3.9"
            - name: install-deps
              run: pip install -r requirements/docs.txt
            - name: make-docs
              run: cd docs && make html
            - name: publish-docs
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./docs/_build/html

    publish:
        needs: [tests]
        runs-on: ubuntu-latest
        concurrency: release
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: publish
              uses: sweetrpg/python-semantic-release@master
              with:
                  bump: "--patch"
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  pypi_token: ${{ secrets.PYPI_TOKEN }}

    notify:
        needs: [publish]
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                include:
                    - repo: model-core
                    - repo: db
                    - repo: library-objects
                    - repo: api-core
                    - repo: library-api
                    - repo: web-core
                    - repo: client
                    - repo: library-web
                    - repo: main-web
                    - repo: shared-web
        steps:
            - uses: juztcode/repo-ditpatch-action@v1
              with:
                  event-type: web-core-published
                  token: ${{ secrets.REPO_ACCESS_TOKEN }}
                  repository: sweetrpg/${{ matrix.repo }}
