name: PR

on:
    pull_request:
        branches: [develop]
        paths:
            - "src/**"
            - "tests/**"
            - pyproject.toml
            - uv.lock
            - "docs/**"

jobs:
    tests:
        name: ${{ matrix.name }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                include:
                    - {
                          name: Linux,
                          python: "3.11",
                          os: ubuntu-latest,
                      }
        steps:
            - uses: actions/checkout@v4
            - name: install-uv
              uses: astral-sh/setup-uv@v5
              with:
                  python-version: ${{ matrix.python }}
                  enable-cache: true
            - name: sync-deps
              run: uv sync --group test --frozen
            - name: lint
              run: uvx black --check -t py311 --diff --color src
            - name: tests
              run: uv run pytest -v tests
            - name: coverage-summary
              run: |
                  echo "## Python coverage" >> "$GITHUB_STEP_SUMMARY"
                  echo '```' >> "$GITHUB_STEP_SUMMARY"
                  uv run coverage report -m >> "$GITHUB_STEP_SUMMARY"
                  echo '```' >> "$GITHUB_STEP_SUMMARY"
                  uv run coverage xml
                  uv run coverage html
            - name: upload-coverage-artifact
              uses: actions/upload-artifact@v4
              with:
                  name: coverage-report-${{ matrix.name }}
                  path: |
                      htmlcov/
                      coverage.xml
            - name: coverage-threshold
              continue-on-error: true
              run: uv run coverage report --fail-under=0
